2020-03-14 05:58:10,245 ERROR: Exception on /explore [GET] [in /home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/nicos/PycharmProjects/flask/app/routes.py", line 48, in explore
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2020-03-14 06:37:08,176 INFO: Microblog startup [in /home/nicos/PycharmProjects/flask/app/__init__.py:48]
2020-03-14 06:37:12,294 ERROR: Exception on /index [GET] [in /home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/nicos/PycharmProjects/flask/app/routes.py", line 33, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2020-03-14 06:37:15,815 ERROR: Exception on /index [GET] [in /home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/nicos/PycharmProjects/flask/app/routes.py", line 33, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2020-03-14 06:37:17,572 ERROR: Exception on /index [GET] [in /home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/nicos/PycharmProjects/flask/app/routes.py", line 33, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2020-03-14 06:37:39,892 ERROR: Exception on /user/eder [GET] [in /home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/nicos/PycharmProjects/flask/app/routes.py", line 133, in user
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2020-03-14 06:46:22,393 INFO: Microblog startup [in /home/nicos/PycharmProjects/flask/app/__init__.py:48]
2020-03-14 06:46:43,471 INFO: Microblog startup [in /home/nicos/PycharmProjects/flask/app/__init__.py:48]
2020-03-14 06:46:51,238 INFO: Microblog startup [in /home/nicos/PycharmProjects/flask/app/__init__.py:48]
2020-03-14 06:47:06,191 ERROR: Exception on /user/eder [GET] [in /home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicos/PycharmProjects/untitled/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/nicos/PycharmProjects/flask/app/routes.py", line 133, in user
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
